Updates to STX control PR
davidozog/sandia-shmem pull request #2
Opened 2018-01-11 18:58 UTC by jdinan

Updates to the PR currently posted for SOS.

@davidozog Please review and merge changes as appropriate.

2018-01-11 18:58 UTC, jdinan commented
Note: only the last 4 commits are changes to the PR, the rest came from merging master with the branch.

2018-01-11 22:18 UTC, davidozog requested changes
This looks great on many levels!

What do you think of doing `want_used` instead of `want_unused`?  It's the weirder case, but I have a hunch it would be ever so slightly easier to pickup for someone who hasn't seen the code before.

2018-01-12 01:50 UTC, jdinan commented
Yeah, I've been ruminating on that bit, too.  Here's a rework of that; let me know what you think.

2018-01-12 02:28 UTC, jdinan commented
af48954 ❤️ 
```
$ SHMEM_DEBUG=1 SHMEM_OFI_STX_MAX=4 SHMEM_OFI_STX_ALLOCATOR=random mpiexec -np 1 test/unit/shmem_ctx
Sandia OpenSHMEM 1.4.0rc1
Build information:
  Git Version           v1.4.0rc1-41-gad3a93b2-dirty (wip/stx_control)
  Configure Args        '--prefix=/Users/dinanjam/opt/sos-dev' '--enable-pmi-simple'
                        '--enable-thread-completion'
                        '--with-ofi=/Users/dinanjam/opt/libfabric-1.5.1'
                        '--enable-debug' '--enable-error-checking' 'CC=gcc-7'
                        'CXX=g++-7'
  Build Date            Thu Jan 11 21:18:18 EST 2018
  Build CC              gcc-7
  Build CFLAGS          -std=gnu11 -g -O2 -Wall -g -fvisibility=hidden

[0000] DEBUG: ../../src/init.c:247: shmem_internal_init
[0000]        Sym. heap=0x180000000 len=537919488 -- data=0x100000c87 len=9081
[0000] DEBUG: ../../src/transport_ofi.c:1235: query_for_fabric
[0000]        OFI provider: sockets, fabric: 127.0.0.0/8, domain: lo0
[0000] DEBUG: ../../src/transport_ofi.c:1089: allocate_fabric_resources
[0000]        OFI version: built 1.5, cur. 1.5; provider version: 2.0
[0000] DEBUG: ../../src/transport_ofi.c:530: shmem_transport_ofi_stx_allocate
[0000]        STX[4] = [ 1S 0S 0S 0S ]
[0000] DEBUG: ../../src/transport_ofi.c:530: shmem_transport_ofi_stx_allocate
[0000]        STX[4] = [ 1S 1P 0S 0S ]
[0000] DEBUG: ../../src/transport_ofi.c:530: shmem_transport_ofi_stx_allocate
[0000]        STX[4] = [ 1S 1P 1P 0S ]
[0000] DEBUG: ../../src/transport_ofi.c:530: shmem_transport_ofi_stx_allocate
[0000]        STX[4] = [ 1S 1P 1P 1P ]
[0000] DEBUG: ../../src/transport_ofi.c:491: shmem_transport_ofi_stx_allocate
[0000]        private STX unavailable, falling back to STX sharing
[0000] DEBUG: ../../src/transport_ofi.c:530: shmem_transport_ofi_stx_allocate
[0000]        STX[4] = [ 2S 1P 1P 1P ]
[0000] DEBUG: ../../src/transport_ofi.c:491: shmem_transport_ofi_stx_allocate
[0000]        private STX unavailable, falling back to STX sharing
[0000] DEBUG: ../../src/transport_ofi.c:530: shmem_transport_ofi_stx_allocate
[0000]        STX[4] = [ 3S 1P 1P 1P ]
[0000] DEBUG: ../../src/transport_ofi.c:491: shmem_transport_ofi_stx_allocate
[0000]        private STX unavailable, falling back to STX sharing
[0000] DEBUG: ../../src/transport_ofi.c:530: shmem_transport_ofi_stx_allocate
[0000]        STX[4] = [ 4S 1P 1P 1P ]
[0000] DEBUG: ../../src/transport_ofi.c:491: shmem_transport_ofi_stx_allocate
[0000]        private STX unavailable, falling back to STX sharing
[0000] DEBUG: ../../src/transport_ofi.c:530: shmem_transport_ofi_stx_allocate
[0000]        STX[4] = [ 5S 1P 1P 1P ]
[0000] DEBUG: ../../src/transport_ofi.c:491: shmem_transport_ofi_stx_allocate
[0000]        private STX unavailable, falling back to STX sharing
[0000] DEBUG: ../../src/transport_ofi.c:530: shmem_transport_ofi_stx_allocate
[0000]        STX[4] = [ 6S 1P 1P 1P ]
```

2018-01-12 16:57 UTC, davidozog commented on src/transport_ofi.c
> +            if (is_unused) {
Does the `e` buffer leak if `is_unused == 0`?

2018-01-12 16:57 UTC, davidozog commented on src/transport_ofi.c
> +    /* TODO: Optimize this case? else if (ctx->options & SHMEM_CTX_PRIVATE) */
Not sure I understand this comment... Do you mean `else if (!(ctx->options & SHMEM_CTX_PRIVATE))` with an `else {RAISE_ERROR...}`, or do you mean something else?

2018-01-12 16:57 UTC, davidozog commented on src/transport_ofi.c
> +         * a shared STX before allocating the next one. */
👍   So we'd have a threshold in `search_unused` that applies only shared contexts?

2018-01-12 16:57 UTC, davidozog commented on src/transport_ofi.c
> +    int               is_private;
Any particular reason not to use `<stdbool.h>`?

2018-01-12 17:00 UTC, davidozog approved these changes

2018-01-12 20:03 UTC, merged