[WIP]Added Unit test to check max number of teams that can be created
davidozog/sandia-shmem pull request #6
Opened 2019-11-05 19:52 UTC by rdesai16

2019-11-06 22:18 UTC, davidozog requested changes
Thanks for the test Rujal!  I have a few requests.

2019-11-06 22:18 UTC, davidozog commented on test/shmemx/shmemx_team_max.c
> +    shmemx_team_t new_team[64];
Let's replace 64 here with `NUM_TEAMS`.

2019-11-06 22:18 UTC, davidozog commented on test/shmemx/shmemx_team_max.c
> +        team_idx = (me*3)+i;
Since the `new_team` array is not a symmetric array, it should ok to use `i` for the index.  Does that make sense?

2019-11-06 22:18 UTC, davidozog commented on test/shmemx/shmemx_team_max.c
> +                printf("Try to destroy some teams...\n");
We might as well call `shmemx_team_destroy` here on `new_team[team_idx]` and make sure the application can recover and call `shmemx_team_split_strided` again.  If not, the unit test should try to return nonzero.

2019-11-06 22:18 UTC, davidozog commented on test/shmemx/shmemx_team_max.c
> +    for (i = 0; i < 3; i++) {
We can probably do `NUM_TEAMS` iterations as well.  We likely won't run out of teams with only 3 split operations.

2019-12-04 18:34 UTC, davidozog commented
@rdesai16 - Correct me if I'm wrong, but this test was merged into SOS master in this PR https://github.com/Sandia-OpenSHMEM/SOS/pull/911, right?  If so, can we close this PR?

2019-12-05 15:22 UTC, rdesai16 commented
@davidozog Yes that's right. We can close this PR now. I'll close it.

2019-12-05 15:22 UTC, closed without merging